using System;
using System.Collections.Generic;


public class PlaceableDatabase : TileDatabase
{
	
	
	 
	public override Dictionary<string, Dictionary<string, string>> SubEntries { get; set; } = new Dictionary<string, Dictionary<string, string>>
	{
		{
			"Decoration",
			new Dictionary<string, string>
			{
				{
					"Pottery",
					Manager.paletteDividerGuid
				},
				{
					"pot",
					"pot"
				},
				{
					"blue_pot",
					"Default Pot Blue"
				},
				{
					"tall_pot",
					"Tall Pot"
				},
				{
					"broken_pot",
					"default pot broken"
				},
				{
					"ash_pot",
					"forge_ash_pot_01"
				},
				{
					"maggot_pot",
					"hell pot full"
				},
				{
					"urn",
					"default urn"
				},
				{
					"gold_vase",
					"gold_vase"
				},
				{
					"stone_urn",
					"stone_urn"
				},
				{
					"Barrels",
					Manager.paletteDividerGuid
				},
				{
					"barrel",
					"barrel_collection"
				},
				{
					"apple_barrel",
					"barrel_apple"
				},
				{
					"barrelman_down",
					"barrelman_down"
				},
				{
					"barrelman_up",
					"barrelman_up"
				},
				{
					"metal_bar_barrel",
					"barrel full of rods"
				},
				{
					"burning_barrel",
					"burning_barrel"
				},
				{
					"Boxes and Crates",
					Manager.paletteDividerGuid
				},
				{
					"crate",
					"crate"
				},
				{
					"big_crate_vertical",
					"default crate long"
				},
				{
					"big_crate_horizontal",
					"default crate wide"
				},
				{
					"metal_crate",
					"metal_crate"
				},
				{
					"cardboard_box_verticalseam",
					"cardboard_box_verticalseam"
				},
				{
					"cardboard_box_horizontalseam",
					"cardboard_box_horizontalseam"
				},
				{
					"cardboard_box_open",
					"cardboard_box_open"
				},
				{
					"crate_wall_left",
					"crate_wall_left"
				},
				{
					"crate_wall_right",
					"crate_wall_right"
				},
				{
					"Plants",
					Manager.paletteDividerGuid
				},
				{
					"bush",
					"bush"
				},
				{
					"bush_flowers",
					"bush flowers"
				},
				{
					"potted_fern",
					"potted_fern"
				},
				{
					"potted_office_plant",
					"potted_office_plant"
				},
				{
					"potted_plant_long_vertical",
					"potted_plant_long_vertical"
				},
				{
					"potted_plant_long_horizontal",
					"potted_plant_long_horizontal"
				},
				{
					"Candles",
					Manager.paletteDividerGuid
				},
				{
					"random_candles",
					"candles"
				},
				{
					"one_candle",
					"candle"
				},
				{
					"two_candles",
					"doublecandle"
				},
				{
					"three_candles",
					"triplecandle"
				},
				{
					"random_sometimes_candles",
					"candles_chance"
				},
				{
					"floating_candle",
					"floatingcandle"
				},
				{
					"cheese_candle_short",
					"cheese_candle_short"
				},
				{
					"cheese_candle_medium",
					"cheese_candle_medium"
				},
				{
					"cheese_candle_tall",
					"cheese_candle_tall"
				},
				{
					"cheese_candle_red",
					"cheese_candle_red"
				},
				{
					"inanimate_candle_kin",
					"bulletman_candle_a"
				},
				{
					"Rocks and Ice",
					Manager.paletteDividerGuid
				},
				{
					"rock",
					"rock"
				},
				{
					"stalagmite_large",
					"stalagmite_large"
				},
				{
					"stalagmite_medium",
					"stalagmite_medium"
				},
				{
					"floor_stones_1",
					"floor_stones_1"
				},
				{
					"floor_stones_2",
					"floor_stones_2"
				},
				{
					"floor_stones_3",
					"floor_stones_3"
				},
				{
					"floor_stones_4",
					"floor_stones_4"
				},
				{
					"ice_spike_large",
					"ice_spike_large"
				},
				{
					"ice_spike_medium",
					"ice_spike_medium"
				},
				{
					"ice_spike_small1",
					"ice_spike_small1"
				},
				{
					"ice_spike_small2",
					"ice_spike_small2"
				},
				{
					"Statues",
					Manager.paletteDividerGuid
				},
				{
					"random_statue",
					"rat figure random"
				},
				{
					"statue_bullet",
					"ratfigure_bullet"
				},
				{
					"statue_convict",
					"ratfigure_convict"
				},
				{
					"statue_hunter",
					"ratfigure_hunter"
				},
				{
					"statue_pilot",
					"ratfigure_pilot"
				},
				{
					"statue_robot",
					"ratfigure_robot"
				},
				{
					"statue_marine",
					"ratfigure_soldier"
				},
				{
					"random_sarcophagus",
					"sarcophogus"
				},
				{
					"sarcophagus_bulletshield",
					"sarcophagus_bulletshield"
				},
				{
					"sarcophagus_bulletsword",
					"sarcophagus_bulletsword"
				},
				{
					"sarcophagus_shotgunbook",
					"sarcophagus_shotgunbook"
				},
				{
					"sarcophagus_shotgunmace",
					"sarcophagus_shotgunmace"
				},
				{
					"kaliber_statue",
					"bulletkingoldwall_statue"
				},
				{
					"gargoyle_blood_fountain",
					"bulletkingoldwall_blood_font"
				},
				{
					"gargoyle_statue",
					"gargoyle_statue"
				},
				{
					"Furniture",
					Manager.paletteDividerGuid
				},
				{
					"bench_vertical",
					"monk_bench_tall"
				},
				{
					"bench_horizontal",
					"monk_bench_long"
				},
				{
					"pink_bench",
					"pink_bench_001"
				},
				{
					"pew",
					"pew"
				},
				{
					"kitchen_chair_front",
					"kitchen_chair_front"
				},
				{
					"kitchen_chair_left",
					"kitchen_chair_left"
				},
				{
					"kitchen_chair_right",
					"kitchen_chair_right"
				},
				{
					"armchair_front",
					"armchair_front"
				},
				{
					"armchair_left",
					"armchair_left"
				},
				{
					"armchair_right",
					"armchair_right"
				},
				{
					"couch_left",
					"couch_left"
				},
				{
					"couch_right",
					"couch_right"
				},
				{
					"blacksmith_lounger",
					"blacksmith_lounger"
				},
				{
					"golden_throne",
					"golden_throne"
				},
				{
					"cell_toilet",
					"cell_toilet"
				},
				{
					"toilet_north",
					"toilet_north"
				},
				{
					"toilet_west",
					"toilet_west"
				},
				{
					"toilet_east",
					"toilet_east"
				},
				{
					"wood_pedestal",
					"wooden_pedestal_001"
				},
				{
					"kitchen_counter",
					"kitchen_counter"
				},
				{
					"manuscript_table_empty",
					"manuscript_table_empty"
				},
				{
					"manuscript_table_closed",
					"manuscript_table_closed"
				},
				{
					"manuscript_table_open",
					"manuscript_table_open"
				},
				{
					"manuscript_table_side",
					"manuscript_table_side"
				},
				{
					"dark_shelf_skulljar",
					"dark_shelf_skulljar"
				},
				{
					"dark_shelf_globe",
					"dark_shelf_globe"
				},
				{
					"dark_shelf_magnifyingglass",
					"dark_shelf_magnifyingglass"
				},
				{
					"dark_shelf_vials",
					"dark_shelf_vials"
				},
				{
					"dark_shelf_emptyjar",
					"dark_shelf_emptyjar"
				},
				{
					"large_boss_desk",
					"large_boss_desk"
				},
				{
					"blacksmith_workbench",
					"blacksmith_workbench"
				},
				{
					"round_shop_table",
					"shoptable"
				},
				{
					"cabinet",
					"wine_cabinet"
				},
				{
					"wine_rack",
					"wine_rack_001"
				},
				{
					"pillory",
					"pillory"
				},
				{
					"shabby_shelf_1",
					"shabby_shelf_1"
				},
				{
					"shabby_shelf_2",
					"shabby_shelf_2"
				},
				{
					"glass_case_pedestal",
					"shop_specialcase"
				},
				{
					"ratty_carpet",
					"ratty_carpet_001"
				},
				{
					"Skulls and Skeletons",
					Manager.paletteDividerGuid
				},
				{
					"pile_of_skulls",
					"catacombs_skull_pile"
				},
				{
					"big_skull_down",
					"big_skull_001"
				},
				{
					"big_skull_left",
					"big_skull_002"
				},
				{
					"big_skull_right",
					"big_skull_003"
				},
				{
					"sitting_skeleton_left",
					"skeleton_left_sit_corner"
				},
				{
					"sitting_skeleton_right",
					"skeleton_right_sit_corner"
				},
				{
					"Bullet Kin",
					Manager.paletteDividerGuid
				},
				{
					"writhing_bulletkin",
					"writhing bulletman"
				},
				{
					"ash_bulletman",
					"ash_bulletman"
				},
				{
					"ash_shotgun_man",
					"ash_shotgunman"
				},
				{
					"Torches and Lights",
					Manager.paletteDividerGuid
				},
				{
					"green_lantern",
					"Shrine_Lantern"
				},
				{
					"purple_lantern",
					"Purple_Lantern"
				},
				{
					"blue_torch",
					"defaulttorchblue"
				},
				{
					"blue_torch_side",
					"defaulttorchsideblue"
				},
				{
					"rotating_green_thing",
					"rotating_green_thing"
				},
				{
					"floating_magic_orb",
					"floating_magic_orb"
				},
				{
					"People",
					Manager.paletteDividerGuid
				},
				{
					"npc_cultist_bowback",
					"cultistbaldbowback_cutout"
				},
				{
					"npc_cultist_bowright",
					"cultistbaldbowbackleft_cutout"
				},
				{
					"npc_cultist_bowleft",
					"cultistbaldbowbackright_cutout"
				},
				{
					"npc_cultist_hooded_facingaway",
					"cultisthoodbowback_cutout"
				},
				{
					"npc_cultist_hooded_facingright",
					"cultisthoodbowleft_cutout"
				},
				{
					"npc_cultist_hooded_facingleft",
					"cultisthoodbowright_cutout"
				},
				{
					"unconscious_soldier_1",
					"unconscious_soldier_1"
				},
				{
					"unconscious_soldier_2",
					"unconscious_soldier_2"
				},
				{
					"green_marine_left",
					"green_marine_left"
				},
				{
					"green_marine_right",
					"green_marine_right"
				},
				{
					"red_marine_left",
					"red_marine_left"
				},
				{
					"red_marine_right",
					"red_marine_right"
				},
				{
					"scientist_blair",
					"scientist_blair"
				},
				{
					"scientist_childs",
					"scientist_childs"
				},
				{
					"scientist_copper",
					"scientist_copper"
				},
				{
					"scientist_dukes",
					"scientist_dukes"
				},
				{
					"scientist_gene",
					"scientist_gene"
				},
				{
					"scientist_macready",
					"scientist_macready"
				},
				{
					"scientist_windows",
					"scientist_windows"
				},
				{
					"dancer_1",
					"dancer_1"
				},
				{
					"dancer_2",
					"dancer_2"
				},
				{
					"dancer_3",
					"dancer_3"
				},
				{
					"dancer_4",
					"dancer_4"
				},
				{
					"dancer_5",
					"dancer_5"
				},
				{
					"dancer_6",
					"dancer_6"
				},
				{
					"dancer_7",
					"dancer_7"
				},
				{
					"Computers and Machines",
					Manager.paletteDividerGuid
				},
				{
					"wide_computer_breakable",
					"wide_computer_breakable"
				},
				{
					"tall_computer_breakable",
					"tall_computer_breakable"
				},
				{
					"water_cooler",
					"water_cooler"
				},
				{
					"water_cooler_side",
					"water_cooler_side"
				},
				{
					"air_conditioning_unit",
					"air_conditioning_unit"
				},
				{
					"ventilation_pipe",
					"ventilation_pipe"
				},
				{
					"roof_vent",
					"roof_vent"
				},
				{
					"wall_gear_north",
					"wall_gear_north"
				},
				{
					"wall_gear_west",
					"wall_gear_west"
				},
				{
					"wall_gear_east",
					"wall_gear_east"
				},
				{
					"npc_synerscope_right",
					"npc_synerscope_left"
				},
				{
					"npc_synerscope_left",
					"npc_synerscope_right"
				},
				{
					"computer_wall",
					"computer_wall"
				},
				{
					"cryotank_right",
					"cryotank_right"
				},
				{
					"cryotank_left",
					"cryotank_left"
				},
				{
					"decor_cables",
					"decor_cables"
				},
				{
					"purple_machine_pedestal",
					"purple_machine_pedestal"
				},
				{
					"broken_car_horizontal",
					"broken_car_horizontal"
				},
				{
					"broken_car_vertical",
					"broken_car_vertical"
				},
				{
					"broken_car_diagonal_northeast",
					"broken_car_diagonal_northeast"
				},
				{
					"broken_car_diagonal_northwest",
					"broken_car_diagonal_northwest"
				},
				{
					"Walls and Dividers",
					Manager.paletteDividerGuid
				},
				{
					"bathroom_stall_divider_north",
					"bathroom_stall_divider_north"
				},
				{
					"bathroom_stall_divider_west",
					"bathroom_stall_divider_west"
				},
				{
					"bathroom_stall_divider_east",
					"bathroom_stall_divider_east"
				},
				{
					"glass_wall_vertical",
					"glass_wall_vertical"
				},
				{
					"glass_wall_horizontal",
					"glass_wall_horizontal"
				},
				{
					"hologram_wall_vertical",
					"hologram_wall_vertical"
				},
				{
					"hologram_wall_horizontal",
					"hologram_wall_horizontal"
				},
				{
					"Miscellaneous Decoration",
					Manager.paletteDividerGuid
				},
				{
					"suit_of_armour",
					"suitofarmor"
				},
				{
					"globe",
					"Table_Globe"
				},
				{
					"stack_of_books",
					"pileorstackofbooks"
				},
				{
					"bunsen_burner",
					"bunson_burner"
				},
				{
					"telescope",
					"telescope"
				},
				{
					"anvil_left",
					"anvil_left"
				},
				{
					"anvil_right",
					"anvil_right"
				},
				{
					"stack_of_wood",
					"stack_of_wood"
				},
				{
					"upturned_minecart",
					"upturned_minecart"
				},
				{
					"trashbag_center",
					"trashbag_center"
				},
				{
					"trashbag_left",
					"trashbag_left"
				},
				{
					"trashbag_right",
					"trashbag_right"
				},
				{
					"alien_tank",
					"alien_tank"
				},
				{
					"wet_floor_sign",
					"wet_floor_sign"
				},
				{
					"shovel",
					"shovel"
				},
				{
					"mop_and_bucket",
					"mop_and_bucket"
				},
				{
					"sold_out_card",
					"sign_soldout"
				},
				{
					"maintenance_sign",
					"elevatormaintenancesign"
				},
				{
					"decorative_papers",
					"decorative_papers"
				},
				{
					"chest_platform",
					"gungeon_treasure_dais"
				},
				{
					"chest_platform_carpet",
					"treasure_dais_stone_carpet"
				},
				{
					"chandelier",
					"Hanging_Chandelier"
				},
				{
					"hanging_pot",
					"Hanging_Pot"
				},
				{
					"molten_metal_wall_bowl",
					"molten_metal_wall_bowl"
				},
				{
					"cartstub_east",
					"cartstub_east"
				},
				{
					"cartstub_west",
					"cartstub_west"
				},
				{
					"cartstub_north",
					"cartstub_north"
				},
				{
					"cartstub_south",
					"cartstub_south"
				},
				{
					"techno_floor_cell_empty",
					"techno_floor_cell_empty"
				},
				{
					"techno_floor_cell_caterpillar",
					"techno_floor_cell_caterpillar"
				},
				{
					"techno_floor_cell_leever",
					"techno_floor_cell_leever"
				},
				{
					"techno_floor_cell_spider",
					"techno_floor_cell_spider"
				},
				{
					"agunim_boss_matt",
					"agunim_boss_matt"
				},
				{
					"lonks_backpack",
					"npc_lostadventurer_backpack"
				},
				{
					"lonks_shield",
					"npc_lostadventurer_shield"
				},
				{
					"lonks_sword",
					"npc_lostadventurer_sword"
				},
				{
					"gatling_gull_nest",
					"gatlinggullnest"
				},
				{
					"decorative_electric_floor",
					"decorative_electric_floor"
				},
				{
					"machine_frame_ring",
					"machine_frame_ring"
				}
			}
		},
		{
			"Loot",
			new Dictionary<string, string>
			{
				{
					"Miscellaneous Pickups",
					Manager.paletteDividerGuid
				},
				{
					"random_pickup",
					"secret_room_pickup_placeable_garaunteed"
				},
				{
					"key",
					"keybullet placeable"
				},
				{
					"blank",
					"blank"
				},
				{
					"ammo",
					"ammo_pickup"
				},
				{
					"spread_ammo",
					"ammo_pickup_spread"
				},
				{
					"armor_pickup",
					"armor_pickup"
				},
				{
					"fifty_casing_pickup",
					"fifty_casing_pickup"
				},
				{
					"five_casing_pickup",
					"five_casing_pickup"
				},
				{
					"glass_guon_pickup",
					"glass_guon_pickup"
				},
				{
					"half_heart_pickup",
					"half_heart_pickup"
				},
				{
					"heart_pickup",
					"heart_pickup"
				},
				{
					"map_pickup",
					"map_pickup"
				},
				{
					"rat_key_pickup",
					"rat_key_pickup"
				},
				{
					"single_casing_pickup",
					"single_casing_pickup"
				},
				{
					"Chests",
					Manager.paletteDividerGuid
				},
				{
					"double_loot_brown_chest",
					"Chest_Wood_Two_Items"
				},
				{
					"blue_chest",
					"chest_silver"
				},
				{
					"green_chest",
					"chest_green"
				},
				{
					"red_chest",
					"chest_red"
				},
				{
					"black_chest",
					"chest_black"
				},
				{
					"rainbow_chest",
					"chest_rainbow"
				},
				{
					"rat_chest",
					"chest_rat"
				},
				{
					"truth_chest",
					"TruthChest"
				},
				{
					"synergy_chest",
					"chest_synergy"
				},
				{
					"random_chest",
					"aaa_floorchestplacer"
				},
				{
					"random_mimic_chest",
					"almostdefinitelyamimicchestplacer"
				},
				{
					"random_unlocked_chest",
					"secretroomfloorchestunlocked"
				},
				{
					"high_dragunfire_chest",
					"highdragunfire_chest_red"
				}
			}
		},
		{
			"Traps",
			new Dictionary<string, string>
			{
				{
					"Floor Hazards",
					Manager.paletteDividerGuid
				},
				{
					"floor_spikes",
					"trap_spike_gungeon_2x2"
				},
				{
					"flame_trap",
					"trap_flame_poofy_gungeon_1x1"
				},
				{
					"pitfall_trap",
					"trap_pit_gungeon_trigger_2x2"
				},
				{
					"web_circle",
					"webplaceable"
				},
				{
					"Turrets and Shooters",
					Manager.paletteDividerGuid
				},
				{
					"forge_shoot_face_west",
					"forge_face_shootseast"
				},
				{
					"forge_shoot_face_north",
					"forge_face_shootssouth"
				},
				{
					"forge_shoot_face_east",
					"forge_face_shootswest"
				},
				{
					"flameburst_trap",
					"flameburst_trap"
				},
				{
					"firebar_trap",
					"firebar_trap"
				},
				{
					"Miscellaneous Traps",
					Manager.paletteDividerGuid
				},
				{
					"curse_pot",
					"curse pot"
				},
				{
					"horizontal_crusher",
					"horizontal_crusher"
				},
				{
					"vertical_crusher",
					"vertical_crusher"
				},
				{
					"flame_pipe_north",
					"flame_pipe_north"
				},
				{
					"flame_pipe_west",
					"flame_pipe_west"
				},
				{
					"flame_pipe_east",
					"flame_pipe_east"
				},
				{
					"dead_blow",
					"customsetupdeadblow"
				},
				{
					"Pathing Traps",
					Manager.paletteDividerGuid
				},
				{
					"sawblade",
					"saw_blade_pathing"
				},
				{
					"minecart",
					"minecart_pathing"
				},
			}
		},
		{
			"NPCs",
			new Dictionary<string, string>
			{
				{
					"Merchants",
					Manager.paletteDividerGuid
				},
				{
					"npc_blacksmith",
					"npc_blacksmith"
				},
				{
					"old_red",
					"Merchant_Blank"
				},
				{
					"cursula",
					"Merchant_Curse"
				},
				{
					"flynt",
					"Merchant_Key"
				},
				{
					"trorc",
					"Merchant_Truck"
				},
				{
					"professor_goopton",
					"NPC_Goop_Merchant"
				},
				{
					"rat_merchant",
					"merchant_rat_placeable"
				},
				{
					"Other Useful NPCs",
					Manager.paletteDividerGuid
				},
				{
					"random_npc",
					"shopannex_contents_01"
				},
				{
					"vampire",
					"NPC_Vampire"
				},
				{
					"sell_creep",
					"SellPit"
				},
				{
					"old_man",
					"NPC_Old_Man"
				},
				{
					"monster_manuel",
					"NPC_Monster_Manuel"
				},
				{
					"brother_albern",
					"NPC_Truth_Knower"
				},
				{
					"synergrace",
					"NPC_Synergrace"
				},
				{
					"patches_and_mendy",
					"NPC_Smash_Tent"
				},
				{
					"witches",
					"NPC_Witches"
				},
				{
					"muncher",
					"NPC_GunberMuncher"
				},
				{
					"evil_muncher",
					"NPC_GunberMuncher_Evil"
				},
				{
					"baby_dragun",
					"babydragunjail"
				},
				{
					"Decorative NPCs",
					Manager.paletteDividerGuid
				},
				{
					"npc_cultist_interactible",
					"cultistbaldbowleft_cutout"
				},
				{
					"npc_henchman",
					"npc_henchman"
				},
				{
					"npc_tootscraze",
					"npc_tootscraze"
				},
				{
					"npc_dyingscientist",
					"npc_dyingscientist"
				}
			}
		}
	};

	
	
	 
	public override Dictionary<string, string> Entries { get; set; } = new Dictionary<string, string>
	{
		{
			"Tables and Flippables",
			Manager.paletteDividerGuid
		},
		{
			"adaptive_table_horizontal",
			"horizontal table"
		},
		{
			"adaptive_table_vertical",
			"vertical table"
		},
		{
			"table_horizontal",
			"Table_Horizontal"
		},
		{
			"table_vertical",
			"Table_Vertical"
		},
		{
			"stone_table_horizontal",
			"Table_Horizontal_Stone"
		},
		{
			"stone_table_vertical",
			"Table_Vertical_Stone"
		},
		{
			"coffin_vertical",
			"Coffin_Vertical"
		},
		{
			"coffin_horizontal",
			"Coffin_Horizontal"
		},
		{
			"table_steel_horizontal",
			"table_steel_horizontal"
		},
		{
			"table_steel_vertical",
			"table_steel_vertical"
		},
		{
			"folding_table",
			"folding_table"
		},
		{
			"Kickable Barrels",
			Manager.paletteDividerGuid
		},
		{
			"random_drum",
			"drum_variety"
		},
		{
			"poison_drum",
			"Yellow Drum"
		},
		{
			"explosive_drum",
			"Red Drum"
		},
		{
			"water_drum",
			"Blue Drum"
		},
		{
			"oil_drum",
			"Purple Drum"
		},
		{
			"explosive_barrel",
			"Red Barrel"
		},
		{
			"custom_barrel",
			"custom_barrel"
		},
		{
			"Other Kickables",
			Manager.paletteDividerGuid
		},
		{
			"ice_cube_bomb",
			"Ice Cube Bomb"
		},
		{
			"brazier",
			"brazier"
		},
		{
			"Shrines",
			Manager.paletteDividerGuid
		},
		{
			"random_shrine",
			"whichshrinewillitbe"
		},
		{
			"ammo_shrine",
			"Shrine_Ammo"
		},
		{
			"beholster_shrine",
			"Shrine_Beholster"
		},
		{
			"blank_shrine",
			"Shrine_Blank"
		},
		{
			"blood_shrine",
			"Shrine_Blood"
		},
		{
			"cleanse_shrine",
			"Shrine_Cleanse"
		},
		{
			"companion_shrine",
			"Shrine_Companion"
		},
		{
			"dice_shrine",
			"Shrine_Dice"
		},
		{
			"angel_shrine",
			"Shrine_FallenAngel"
		},
		{
			"glass_shrine",
			"Shrine_Glass"
		},
		{
			"health_shrine",
			"Shrine_Health"
		},
		{
			"hero_shrine",
			"Shrine_Hero"
		},
		{
			"junk_shrine",
			"Shrine_Junk"
		},
		{
			"cursed_mirror",
			"Shrine_Mirror"
		},
		{
			"yv_shrine",
			"Shrine_YV"
		},
		{
			"Doors",
			Manager.paletteDividerGuid
		},
		{
			"locked_door",
			"SimpleLockedDoor"
		},
		{
			"default_door_vertical",
			"IronWoodDoor_Vertical"
		},
		{
			"default_door_horizontal",
			"IronWoodDoor_Horizontal"
		},
		{
			"jail_cell_door",
			"jaildoor"
		},
		{
			"Misc",
			Manager.paletteDividerGuid
		},
		{
			"heart_dispenser",
			"HeartDispenser"
		},
		{
			"teleporter",
			"teleporter"
		},
		{
			"elevator_arrival",
			"elevator_arrival"
		},
		{
			"elevator_departure",
			"elevator_departure"
		},
		{
			"abbey_entrance_altar",
			"gungeoncreststairs"
		},
		{
			"Random Enemy Selectors",
			Manager.paletteDividerGuid
		},
		{
			"random_easy_keep_enemy",
			"castle_01_easy"
		},
		{
			"random_medium_keep_enemy",
			"castle_02_medium"
		},
		{
			"random_hard_keep_enemy",
			"castle_03_hard"
		},
		{
			"random_easy_gungeon_enemy",
			"gungeon_01_easy"
		},
		{
			"random_medium_gungeon_enemy",
			"gungeon_02_medium"
		},
		{
			"random_hard_gungeon_enemy",
			"gungeon_03_hard"
		},
		{
			"random_medium_mines_enemy",
			"mines_02_medium"
		},
		{
			"random_red_blue_vet_shotgun",
			"shotgunguysallvariants"
		},
		{
			"random_bulletkin",
			"bulletman_variety"
		},
		{
			"random_bulletkin_skullet",
			"hollow_bulletman_cocktail"
		},
		{
			"random_redshotgun_bulletkin",
			"proceduraltable_01_castle"
		},
		{
			"random_blobulon_pinhead",
			"blob or grenade"
		},
		{
			"random_cubulon_appgunjurer",
			"cubulon_or_yellow wizard"
		},
		{
			"random_hollowpoint_appgunjurer",
			"ghost_or_yellowwizard"
		},
		{
			"random_bookllet",
			"angrybook_variety"
		},
		{
			"random_tier_blob",
			"blobulon_tiers"
		},
		{
			"random_tier_poisonblob",
			"poisbulon variety"
		},
		{
			"random_bullat",
			"bullat_variety"
		},
		{
			"random_bookllet_gigi_appgunjurer",
			"yellow_wizard_book_bird_combo"
		},
		{
			"random_kingbullat_chancebulon",
			"king bullat or chancebulon"
		},
		{
			"random_gunnut_leadmaiden",
			"lead maiden or gunnut"
		},
		{
			"random_rubberkin_tazie",
			"rubberbullet or tazie"
		},
		{
			"random_snipershell_professional",
			"rifleman or professional"
		},
		{
			"random_cubulon_wizbang_skullet",
			"cube_n_wizbang_n_skullets"
		},
		{
			"random_cubulon_cubulead",
			"cubecocktail"
		},
		{
			"random_gripmaster_redshotgun_blueshotgun",
			"gripmaster_for_castle"
		},
		{
			"random_sometimes_tarnisher_blueshotgun",
			"tarnisher sometimes"
		},
		{
			"random_sometimes_rubberkin",
			"maybe rubber bulletman"
		},
		{
			"random_sometimes_pinhead",
			"maybe grenade guy"
		},
		{
			"random_sometimes_gunsinger",
			"lead wizard_maybe"
		},
		{
			"random_sometimes_gripmaster",
			"gripmaster sometimes"
		},
        {
			"Custom",
			Manager.paletteDividerGuid
		}
	};
}
